print("hello")

#varible

In [4]:
name = "shruti"
print(name)
print(type(name))

shruti
<class 'str'>

# Variables

In [9]:
x= 1
b=3,2
c = "shruti"
print(c)
d = True
a = False
e = 4+7j

print(type(x))
print(type(b))
print(type(d))
print(type(a))
print(type(e))

shruti
<class 'int'>
<class 'tuple'>
<class 'bool'>
<class 'bool'>
<class 'complex'>

In [29]:
# index always start with zero 0.
# indexing

In [4]:
name = "sachin"
#index 012345
name[0]

's'

In [5]:
print(name[2])

c

In [10]:
text = 'hie Everyone !'
print(text)
print(text[8])

hie Everyone !
y

In [16]:
len(text) # it cannot be aplied for numbers it count

14

In [18]:
num = 3045        #type casting
num_1 = str(num)
print(type(num))
print(type(num_1))
print(len(num_1))

<class 'int'>
<class 'str'>
4

# conversion

In [20]:
x= 4  # int to numbers conversion

print(x)
print (type(x))

x= int (x)
print(x)
print(type(x))

4
<class 'int'>
4
<class 'int'>

In [23]:
x= 4.3  # int to numbers conversion

print(x)
print (type(x))

x= int (x)
print(x)
print(type(x))

4.3
<class 'float'>
4
<class 'int'>

In [24]:
x= '4'  # int to numbers conversion

print(x)
print (type(x))

x= int (x)
print(x)
print(type(x))

4
<class 'str'>
4
<class 'int'>

In [28]:
x= '45.8' # int to numbers conversion

print(x)
print (type(x)) 

x= float(x)
print(x)
print(type(x))

x= int (x)
print(x)
print(type(x)) 

x= bool(x)
print(x)
print(type(x))

x= complex(x)
print(x)
print(type(x))

45.8
<class 'str'>
45.8
<class 'float'>
45
<class 'int'>
True
<class 'bool'>
(1+0j)
<class 'complex'>

# BODMAS

In [32]:
3+7-4/2*3

4.0

In [ ]:
3+7-2*3

3+7-6

In [33]:
10-4

4

In [39]:
3 + True

4

In [40]:
35 + False

35

# Slicing

In [52]:
text = "mahabaleswhar"
# slicing involves [start :stop: step]
text[4:7]
print(len (text))
text[0:9:3]

13

'mal'

In [46]:
print(text[:])

mahabaleswhar

In [53]:
x = -70
print(x)
del (x)
print(x)

-70

NameError: name 'x' is not defined

# Conditional Statement

# if statements

In [70]:
x= 20 
print(x>0)
if x > 0:
    print("number is positive")

print('Program Ends')

True
number is positive
Program Ends

In [76]:
x=-20 
print(x>0)
if x > 0:
    print("number is positive")
else:
     print("number is negative")
    
print('Program Ends')

False
number is negative
Program Ends

In [81]:
x=0 
print(x==0)
if x > 0:
    print("number is positive")

elif x==0:
    print("number is zero")
else:
     print("number is negative")
    
print('Program Ends')

False
number is zero
Program Ends

In [83]:
x=2000 
#print(x==0)
if x > 1000:
    print("number is greater than 1000")

elif x>500:
    print("number lies between 500 and 1000")
else:
     print("number is  less than 500")
    
print('Program Ends')

False
number is greater than 1000
Program Ends

In [84]:
pwd()

'C:\\Users\\Asus'

In [28]:
percent = int(input('please provide your marks'))
if percent >90 :
    print (" You must try in medical") 
    
elif percent >80 and percent <=90 :
    print("Architecture can be suitable for you")
    
elif percent >60 and percent <=80:
    print("Enginerring is best for you ")
    
elif percent >30 and percent <=50 :
      print("arts")
else :
      print("better luck for next time")

please provide your marks 88

Architecture can be suitable for you

In [22]:
x = int(input("enter the first number"))
y = int(input("enter thr second number")) 
c = x+y 
print("sum =", c)

enter the first number 2
enter thr second number 3

sum = 5

In [30]:
percent = int(input('please provide your marks'))
if percent >90 :
    print (" You must try in medical") 
    
if percent >80 and percent <=90 :
    print("Architecture can be suitable for you")
    
if percent >60 and percent <=80:
    print("Enginerring is best for you ")
    
if percent >30 and percent <=50 :
      print("arts")
else :
      print("better luck for next time")

please provide your marks 75

Enginerring is best for you
better luck for next time

# loops Statement

In [39]:
# write a program to print 1 to 5
i =1 
while  i<=5:
    print(i)
    i=i+1

1
2
3
4
5

In [48]:
# write a program to 15 to 20
i = 15
while i<=20:
    print(i)
    i=i+1

15
16
17
18
19
20

In [51]:
# write a program to print 1 to 5
i =2 
while  i<=10:
    print(i)
    i=i+2

2
4
6
8
10

In [1]:
# to print 1 to 10 even no.
i=1
while i<=10:
    if i%2==0: # coparison operator
        print(i)
    i= i+1

2
4
6
8
10

In [3]:
# to print 1 to 10 odd no.
i=1
while i<=10:
    if i%2!=0:
        print(i)
    i= i+1

1
3
5
7
9

In [2]:
# write a program to divisible by either 7 or 9
i= 1 
while i<100 :
    if i%7==0 or i%9==0:
        print(i)
    i= i+1

7
9
14
18
21
27
28
35
36
42
45
49
54
56
63
70
72
77
81
84
90
91
98
99

In [5]:
# write a program to 5 to 1
i=5
while i:
    print(i)
    i=i-1

5
4
3
2
1

In [6]:
n = int(input("Enter a number: "))

i = 1
while i <= 10:
    print(n, "*", i, "=", n * i)
    i += 1

Enter a number:  8

8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80

In [8]:
table = int(input("enter the number to see it TABLE: "))

counter = 1
while counter<=10:
    print(table,"X",counter ,"=", table*counter)
    counter+= 1

enter the number to see it TABLE:  5

5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50

# for Loop

In [4]:
for i in range (1,6):
     print(i)

1
2
3
4
5

In [18]:
x=int(input("enter the number"))
for i in range (1,11):
    print (x,"x",i,"=",x*i)

enter the number 22

22 x 1 = 22
22 x 2 = 44
22 x 3 = 66
22 x 4 = 88
22 x 5 = 110
22 x 6 = 132
22 x 7 = 154
22 x 8 = 176
22 x 9 = 198
22 x 10 = 220

In [10]:
# write a program to print odd no.
for i in range (1,11,1):
    if i%2==0:
      print(i)

2
4
6
8
10

In [22]:
# write a program to print prime numbers
n = int(input("Enter a number: "))

if n > 1:
    for i in range(2, n):
        if n % i == 0:
            print("Not a Prime Number")
            break
    else:
        print("Prime Number")
else:
    print("Not a Prime Number")

Enter a number:  53

Prime Number

In [2]:
i= 1
while i<=10:
    if i==7:
        break
    else :
        print(i)
    i= i+1
print ("program ends")

1
2
3
4
5
6
program ends

# continue , break and pass

#  to print a prime number

In [15]:
num = int(input("enter the number"))
divisor=num-1
flag =1
while divisor>=2:
    if num % divisor ==0:
        flag = 0
        break
    else :
        pass
    divisor= divisor-1
if flag ==1 :
    print ("num is prime number")
else:
    print("num is not prime number")

enter the number 12

num is not prime number

# nested loop

In [4]:
i = 1
while i<=3:
    j = 1
    while j<=2:
        print(i,j)
        j=j+1
    i=i+1

1 1
1 2
2 1
2 2
3 1
3 2

In [10]:
i=1
while i<=3:
    j =1
    while j<=2:
        if j==2:
            break
        print(i,j)
        j= j+1
    i=i+1

1 1
2 1
3 1

In [8]:
i=1
while i<=3:
    j =1
    while j<=2:
        k=1
        while k<=2:
           print(i,j,k)
           k = k+1
        j= j+1
    i=i+1

1 1 1
1 1 2
1 2 1
1 2 2
2 1 1
2 1 2
2 2 1
2 2 2
3 1 1
3 1 2
3 2 1
3 2 2

In [17]:
n = int(input("Enter a number: "))
fact = 1

for i in range(1, n + 1):
    fact = fact * i

print("Factorial =", fact)

Enter a number:  4

Factorial = 24

In [21]:
i = 1
while i<=10:
    if i==4:
       i=i+1
       continue
    print(i ,end=" ")
    i = i+1

1 2 3 5 6 7 8 9 10

In [ ]:
a =[ 1,2,3,4,5]

In [6]:
text= "abcd"
i = 0 
while i<=3:
    if i==2:
        i =i+1
        continue
    print(text[i])
    i=i+1

a
b
d

In [5]:
#print number except those divisible by 7
i = 1
while i<=50:
    if i%7==0:
       i=i+1
       continue
    print(i ,end=" ")
    i = i+1

1 2 3 4 5 6 8 9 10 11 12 13 15 16 17 18 19 20 22 23 24 25 26 27 29 30 31 32 33 34 36 37 38 39 40 41 43 44 45 46 47 48 50

In [8]:
i = 1
while i<=10:
    if i==4 or i==7 :
       i=i+1
       continue
    print(i ,end=" ")
    i = i+1

1 2 3 5 6 8 9 10

In [11]:
i = 1
while i<=100:
    if i%7==0 and i%9==0:
       i=i+1
       continue
    print(i ,end=" ")
    i = i+1

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100

In [14]:
x =89
if x==1:
   pass #placeholder 
else :
    print("asdafgh")

asdafgh

In [17]:
list1 = (2,4.3, True)
print(type(list1))
print(list1)

<class 'tuple'>
(2, 4.3, True)

In [18]:
list1 = [2,4.3, True]
print(type(list1))
print(list1)

<class 'list'>
[2, 4.3, True]

In [19]:
list1 = {2,4.3, True}
print(type(list1))
print(list1)

<class 'set'>
{True, 2, 4.3}

In [20]:
list1 = {"a=[1,2]", "b=[1,4]}
print(type(list1))
print(list1)

<class 'set'>
{'b=[1,4]', 'a=[1,2]'}

In [22]:
list1 = (2,4.3, True)
list1[0]

2

In [4]:
list3=[2,1,7]
list3[0]
list3[-3]

2

# pop

In [10]:
list3.pop() # pop is used for delete the last no of the list
print(list3)

[2]

In [13]:
list4=[23,11,9,14]
list4.pop()
print(list4)

[23, 11, 9]

# pop(index)

In [14]:
list4=[23,11,9,14]
list4.pop(1) # used for delete element by index no pop.(index) pop(0)

print(list4)

[23, 9, 14]

# Append

In [15]:
list4=[23,11,9,14]
list4.append(5) # it is used for add single element in list 
print(list4)

[23, 11, 9, 14, 5]

# extend

In [17]:
list1 = [2,11,9,7,8]
list2 = [5,8]
list1.extend(list2) # it is used for adding multiple elements in a list
print(list1)

[2, 11, 9, 7, 8, 5, 8]

# insert

In [25]:
list1 = [2,7,9,5]
list1.insert(2,100) # index element
print(list1)

[2, 7, 100, 9, 5]

In [30]:
list1 = [2,7,9,5]
list2=[11,3]
list1.insert(2,list2)# it used for displaying list under the list also called nested list
print(list1)

[2, 7, [11, 3], 9, 5]

# clear

In [31]:
list1 = [2,7,9,5]
list1.clear()
print(list1)

[]

In [33]:
list1 = [2,7,9,5]
list1.insert(2,100) # index element
print(list1)

[2, 7, 100, 9, 5]

# list Comphrension

In [2]:
currensies =["rupee","dinner","yen","rupeee"]
currensies.index("yen")

2

In [3]:
list2= [*range(11,21,2)]
list2

[11, 13, 15, 17, 19]

In [5]:
list2= [*range(5 ,40,5)]
list2

[5, 10, 15, 20, 25, 30, 35]

In [6]:
list1 = [i for i in range(1,11)]
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
list1=[]
for i in range(1,11):
    list1.append(i)
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
list1 = [i**2 for i in range(1,11)]
list1

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
list1 = [i**2 for i in range(1,11)]
list1

In [3]:
list1=[]
for i in range(1,20):
    list1.append(i**2)
print(list1)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]

#  wap to print whether user entered no is palimdrome

In [ ]:
#palimdrome stands for a number start and ends with same number its is like mirror image for ex ,343 ,555,45454

In [9]:
x = int(input("enter the number to ch if it is palimdrome : "))
x= str(x)
print(len(x))
list1 =[]
for i in x :
    list1.append(i)
print(list1)

flag= False 
for i in range (len(list1)): # range(0,3)
    if list1[i] == list1[-1-i]:

        flag = False
    else:
        flag = True
        break
        
if flag== False:
    print("number is palimdrome")
else:
    print("number is not palimdrome")

enter the number to ch if it is palimdrome :  454

3
['4', '5', '4']
number is palimdrome

# tuple

In [ ]:
# tuple cannot change after declaration it is immutable list can be change after declaration it

In [ ]:
tup1 =(5,6,7,8,9,8)
type(tup1)
#when we apply other aggrements function for tup,it will work some just change the brackets to round

In [7]:
tup1 =(1,2,3,4,5,6,9)  #immutable
print(tup1.index(2)) # index of element 
print(tup1.count(9))
print(tup1[-1]) #negative indexing
print(tup1[6]) #positive indexing
print(sum(tup1))
print(len(tup1))

1
1
9
9
30

In [2]:
list1 = [5,2,3,6,7]    # convert its type to list to tuple
tupl2 = tuple(list1)
print(tupl2)

(5, 2, 3, 6, 7)

In [9]:
tup1 =(5,10,150,4,6,9)
list1 = list(tup1)
print(list1)
del tup1

SyntaxError: invalid syntax (4190748651.py, line 4)

# Dictionary

In [ ]:
# dictionary always declared in { } brackets

In [12]:
dict1 = {3:4} #keys value
type(dict1)

dict

In [16]:
dict1 = {"Name": "Amar"} #{key1:value1,key2:value2....}
dict1.values()

dict_values(['Amar'])

In [17]:
dict1.keys()

dict_keys(['Name'])

In [6]:
report = { "Patient_name":["ajit","Sanjay","Affan"],"fasting_Sugar":[210,180,130]}
import pandas as pd
file = pd.DataFrame(report)
file

  Patient_name  fasting_Sugar
0         ajit            210
1       Sanjay            180
2        Affan            130

In [25]:
pwd()

'C:\\Users\\Asus\\pyhton.git'

In [26]:
file.to_csv("T385_report.csv")
df = pd.read_csv("T385_report.csv")
df

   Unnamed: 0 Patient_name  fasting_Sugar
0           0         ajit            210
1           1       Sanjay            180
2           2        Affan            130

In [7]:
report.keys()

dict_keys(['Patient_name', 'fasting_Sugar'])

In [8]:
report.values()

dict_values([['ajit', 'Sanjay', 'Affan'], [210, 180, 130]])

In [10]:
report.items()

dict_items([('Patient_name', ['ajit', 'Sanjay', 'Affan']), ('fasting_Sugar', [210, 180, 130])])

In [16]:
for i,j in report.items():
    print(i,":",j)

Patient_name : ['ajit', 'Sanjay', 'Affan']
fasting_Sugar : [210, 180, 130]

In [12]:
sample=[(4,5,6),(7,8)]
sample[1][0]

7

In [13]:
jumble = [5,[7,8,2],[6,1,[76,45,[88,99,11]]]]
len(jumble)

3

In [17]:
report["Patient_name"]

['ajit', 'Sanjay', 'Affan']

In [19]:
report["Patient_name"][2] ="Padmnabh"

In [20]:
report

{'Patient_name': ['ajit', 'Sanjay', 'Padmnabh'],
 'fasting_Sugar': [210, 180, 130]}

In [24]:
report["fasting_Sugar"][0]=300

In [22]:
report

{'Patient_name': ['ajit', 'Sanjay', 'Padmnabh'],
 'fasting_Sugar': [300, 180, 130]}

In [2]:
Employee = { "details":{"id":[1,2],"name":["Ram","Ajay"]},
             "salary":[50000,60000]}
type(Employee)

dict

In [3]:
print(Employee.keys())
print(Employee.values())

dict_keys(['details', 'salary'])
dict_values([{'id': [1, 2], 'name': ['Ram', 'Ajay']}, [50000, 60000]])

In [4]:
print(Employee["details"].keys())

dict_keys(['id', 'name'])

In [5]:
print(Employee["details"])

{'id': [1, 2], 'name': ['Ram', 'Ajay']}

In [6]:
print(Employee["details"]["name"])

['Ram', 'Ajay']

In [7]:
print(Employee["details"]["name"][0])

Ram

# SET

In [10]:
set1 ={12,4,63,2,4,6}
print(set1)

{2, 4, 6, 12, 63}

In [12]:
set2 = {"l","e","t","t","e","r"} # duplicates are not alloqed in a set
print(set2)

{'r', 'e', 't', 'l'}

In [13]:
list1 = [23,34,56,34,True,False,True] # list 
set1 = set(list1)
print(set1)

{False, True, 34, 23, 56}

In [17]:
s =set ({})
print(type(s))

<class 'set'>

In [15]:
null_set =set()
print(type(null_set))

<class 'set'>

# set Functions

In [ ]:
# function are add ,update,discard, remove

In [19]:
Fruits = {"Apple","banana"}
Fruits.add("kiwi")
print(Fruits)

{'kiwi', 'banana', 'Apple'}

In [21]:
Fruits = {"Apple","banana"}
Fruits.add(["kiwi","cherry"]) # add will take one element at a time
print(Fruits)

TypeError: cannot use 'list' as a set element (unhashable type: 'list')

In [22]:
F2 =(["kiwi","cherry"])
Fruits = {"Apple","banana"}
for i in F2:
    Fruits.add(i)

Fruits

{'Apple', 'banana', 'cherry', 'kiwi'}

In [24]:
Fruits = {"Apple","banana"}
Fruits.update(["kiwi","cherry","Papaya"]) # update can take multiple element
print(Fruits)

{'Apple', 'cherry', 'Papaya', 'banana', 'kiwi'}

In [25]:
Fruits ={'Apple', 'cherry', 'Papaya', 'banana', 'kiwi'}
Fruits.remove('Papaya')
print(Fruits)

{'kiwi', 'cherry', 'banana', 'Apple'}

In [27]:
Fruits ={'Apple', 'cherry', 'Papaya', 'banana', 'kiwi'}
Fruits.discard('chikoo') # it will not give an error if set han no element we wirrten in discard it will excute 
print(Fruits)

{'kiwi', 'cherry', 'Papaya', 'banana', 'Apple'}

In [29]:
Fruits ={'Apple', 'cherry', 'Papaya', 'banana', 'kiwi'}
Fruits.discard('Papaya') # it will not give an error if set han no element we wirrten in discard it will excute 
print(Fruits)

{'kiwi', 'cherry', 'banana', 'Apple'}

In [31]:
Fruits ={'Apple', 'cherry', 'Papaya', 'banana', 'kiwi'}
Fruits.pop() # pop removes the random no of set generally it will take last number
print(Fruits)

{'cherry', 'Papaya', 'banana', 'Apple'}

In [3]:
A ={12,45,34,23,14,18}
B ={34,44,55,66,14}

# A Intersection B

In [4]:
print(A & B)
print(B & A)

{34, 14}
{34, 14}

In [5]:
c = A.intersection(B)
print(c)

{34, 14}

In [8]:
print( c & A)

{34, 14}

# A Union B

In [10]:
A = {12 ,45,34,23,14,18}
B = {34,44,55,66,14}
print(A | B)

{34, 66, 12, 45, 14, 44, 18, 55, 23}

In [11]:
print(B| A)

{34, 66, 44, 12, 14, 45, 18, 23, 55}

In [12]:
print(A.union(B))

{34, 66, 12, 45, 14, 44, 18, 55, 23}

In [13]:
print(B.union(A))

{34, 66, 44, 12, 14, 45, 18, 23, 55}

In [14]:
A = {12 ,45,34,23,14,18}
B = {34,44,55,66,14}
print(A.difference(B)) # A -B it will take A elements

{18, 12, 45, 23}

In [15]:
A = {12 ,45,34,23,14,18}
B = {34,44,55,66,14}
print(B.difference(A))

{66, 44, 55}

# Functions

# Defined Functon , Anonymous Function

In [38]:
def add (M,N) :
    print(M+N)
def mult(M,N):
    print(M*N)
def sub(M,n):
    print(M-N)
def div(M,N):
    print(M/N)

print("welcome to calculator Program:\n")
choice= int(input( "what would you like to perform:\n Choose: \n1 For addtion \n2 for substraction \n3 for multiplication \n4 for division"))
num1 = int(input("Enter 1st number: "))
num2 = int(input("enter 2nd number: "))
# selection  = {1:add(num1,num2),2:sub(num1,num2),3:mult(num1,num2),4:div (num1,num2)}
# print(selection[choice])
if choice==1:
    add(num1,num2)
elif choice==2:
    sub(num1,num2)
elif choice==3:
    mult(num1,num2)
else :
    div(num1,num2)

welcome to calculator Program:

what would you like to perform:
 Choose:
1 For addtion
2 for substraction
3 for multiplication
4 for division 2
Enter 1st number:  123
enter 2nd number:  456

67

In [ ]:
X,Y = 2,3
M,N =45,56
add(X,Y) # calling of the function
mult(42,51)
mult (9,2)
add (4569,485413)
div(456587,12)
sub(47952,123666